# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact2',
            field=models.IntegerField(null=True),
        ),
    ]
