# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-20 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20181220_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='token',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='token',
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
