# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_auto_20181220_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='last_payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
