# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-22 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0004_statistics_last_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='last_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='remaining',
            field=models.IntegerField(default=0),
        ),
    ]
