# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_auto_20181222_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='session_key',
            field=models.CharField(default='', max_length=50),
        ),
    ]
