# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_owner_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
