# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-02 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0009_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
